name = "json_typedef"
version = "1.0.0"
target = "erlang"
description = "Work with JSON using a schema! RFC8927"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "json-typedef" }
links = [
  { title = "JSON-Typedef", href = "https://jsontypedef.com/" },
  { title = "RFC8927", href = "https://datatracker.ietf.org/doc/html/rfc8927" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.1 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
